version: '3'
services:
  app:
    build: .
    container_name: arduino
    ports:
      - 8000:8000
    environment:
      - MONGO_URI=mongodb://host.docker.internal:27017/demo_v1
    command: sh -c "npm run dev"
    depends_on:
      - mongo_db
    networks:
      - express-mongo-network

  mongo_db:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    networks:
      - express-mongo-network

networks:
  express-mongo-network:
    driver: bridge
